// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjlkIY90ehPyLBKnyphGquxT9YA8IV-RQ',
    appId: '1:558624696603:web:0799a254f5ec8e75530bbe',
    messagingSenderId: '558624696603',
    projectId: 'breathbank-3d6e8',
    authDomain: 'breathbank-3d6e8.firebaseapp.com',
    storageBucket: 'breathbank-3d6e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHfx5ztbOKgiRDb7xMSqn6teL9iJiQNCI',
    appId: '1:558624696603:android:470a13b56f6a2024530bbe',
    messagingSenderId: '558624696603',
    projectId: 'breathbank-3d6e8',
    storageBucket: 'breathbank-3d6e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgdg50zBlZ9dPwZOrCZOAqnwuCpbgSTaU',
    appId: '1:558624696603:ios:eef01df5523a8206530bbe',
    messagingSenderId: '558624696603',
    projectId: 'breathbank-3d6e8',
    storageBucket: 'breathbank-3d6e8.firebasestorage.app',
    iosBundleId: 'com.example.breathBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgdg50zBlZ9dPwZOrCZOAqnwuCpbgSTaU',
    appId: '1:558624696603:ios:eef01df5523a8206530bbe',
    messagingSenderId: '558624696603',
    projectId: 'breathbank-3d6e8',
    storageBucket: 'breathbank-3d6e8.firebasestorage.app',
    iosBundleId: 'com.example.breathBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjlkIY90ehPyLBKnyphGquxT9YA8IV-RQ',
    appId: '1:558624696603:web:2fd687bbd111a8d6530bbe',
    messagingSenderId: '558624696603',
    projectId: 'breathbank-3d6e8',
    authDomain: 'breathbank-3d6e8.firebaseapp.com',
    storageBucket: 'breathbank-3d6e8.firebasestorage.app',
  );
}
