name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'    

      - name: Install dependencies
        run: |
          cd BreathBankApp/breath_bank
          flutter pub get

      - name: Analyze and build
        run: |
          cd BreathBankApp/breath_bank
          flutter build apk --debug

      - name: Run tests with coverage
        run: |
          cd BreathBankApp/breath_bank
          flutter test --coverage
      
      - name: Fix lcov path separators
        run: |
          cd BreathBankApp/breath_bank
          sed -i 's|\\|/|g' coverage/lcov.info

      - name: Print lcov.info contents
        run: |
          cat BreathBankApp/breath_bank/coverage/lcov.info

      - name: List Dart files
        run: |
          find BreathBankApp/breath_bank/lib -name '*.dart'
    
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: BreathBankApp/breath_bank

