name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest  # puede ser mejor que windows-latest para Flutter
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Move to project directory
        run: cd BreathBankApp/breath_bank

      - name: Install dependencies
        run: flutter pub get
        working-directory: BreathBankApp/breath_bank

      - name: Analyze and build
        run: flutter build apk --debug
        working-directory: BreathBankApp/breath_bank

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: BreathBankApp/breath_bank
